#!/bin/sh

COMMAND="$1"
IMAGE_NAME="$2"
OPTION="$3"
MODUL_VERSION="$4"

case "$COMMAND" in
    list)
        docker image list --format '{{.Repository}}\t{{.Tag}}' || exit 2
        ;;
    install)
        # just pulls image and does not start a container
        docker pull $MODUL_VERSION || exit 2
        ;;
    remove)
        docker rmi $MODUL_VERSION || exit 2
        ;;
    prepare)
        ;;
    finalize)
        ;;
    update-list)
        exit 1
        ;;
esac
exit 0